version: '3'

services:
  app:
    build: .
    tty: true
    ports:
      - "3000:3000"
      # 24678 hot reload port
      - "24678:24678"
    volumes:
      - .:/app
      - nodemodules:/app/node_modules
      - next:/app/.next
volumes:
  nodemodules:
  next:
